__all__ = ["ROUTER_SYSTEM_PROMPT", "ROUTER_HUMAN_PROMPT",
           "MEDICAL_REPHRASE_PROMPT", "MEDICAL_ANSWER_PROMPT", "MEDICAL_SYSTEM_PROMPT", "MEDICAL_HISTORY_PROMPT",
           "SPLIT_QUERY_SYSTEM_PROMPT", "SPLIT_QUERY_HUMAN_PROMPT",
           "EVAL_ANSWER_SYSTEM_PROMPT", "EVAL_ANSWER_HUMAN_PROMPT",
           "SUMMARY_SYSTEM_PROMPT", "SUMMARY_HUMAN_PROMPT",
           "FINAL_ANSWER_SYSTEM_PROMPT", "FINAL_ANSWER_HUMAN_PROMPT", "EVAL_PROMPT"]

from .router import ROUTER_SYSTEM_PROMPT, ROUTER_HUMAN_PROMPT
from .medical import MEDICAL_REPHRASE_PROMPT, MEDICAL_ANSWER_PROMPT, MEDICAL_SYSTEM_PROMPT, MEDICAL_HISTORY_PROMPT
from .base import (SPLIT_QUERY_SYSTEM_PROMPT, SPLIT_QUERY_HUMAN_PROMPT, 
                   EVAL_ANSWER_SYSTEM_PROMPT, EVAL_ANSWER_HUMAN_PROMPT,
                   SUMMARY_SYSTEM_PROMPT, SUMMARY_HUMAN_PROMPT,
                   FINAL_ANSWER_SYSTEM_PROMPT, FINAL_ANSWER_HUMAN_PROMPT, EVAL_PROMPT)